ProjectTango/ProjectTango/urls.py
from django.conf.urls import patterns, include, url
from core import views
# Uncomment the next two lines to enable the admin:
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', views.home, name='home'),
    # url(r'^ProjectTango/', include('ProjectTango.ProjectTango.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),

    url(r'^aircraft/', include('aircraft.urls')),
    url(r'^log/', include('aircraft.urls_logs')),
    url(r'^rule/', include('aircraft.urls_rules')),

    # AllAuth URLS
    url(r'^accounts/', include('allauth.urls')),

    # Calendar URLs
    url(r'^schedule/', include('schedule.urls')),

    # Customer
    url(r'^customer/', include('customer.urls')),

    # Invoices
    url(r'^invoice/', include('invoice.urls')),

    # Django rest framework
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),

    # Core app URLs
    url(r'^/', include('core.urls')),


 ) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
print(settings.MEDIA_ROOT)

ProjectTango/core/urls.py
from django.conf.urls import patterns, url
from django.contrib.auth.decorators import login_required, permission_required

from . import views

urlpatterns = patterns("",
    url(r'^profile/pilot/(?P<pk>[-_\w]+)/$', views.home, name='pilot-detail'),
    url(r'^profile/inspector/(?P<pk>[-_\w]+)/$', views.home, name='inspector-detail'),
)

ProjectTango/invoice/urls.py
from django.conf.urls import patterns, url
from django.contrib.auth.decorators import login_required, permission_required

from invoice import views, api

urlpatterns = patterns("",
                       # Receipt
                       url(r"^receipt/$", login_required(views.ReceiptList.as_view()), name="receipt-list"),
                       url(r"^receipt/add/$",
                           permission_required('aircraft.add_aircraft')(views.ReceiptCreate.as_view()),
                           name="receipt-create"),
                       url(r'^receipt/(?P<pk>[-_\w]+)/$', login_required(views.ReceiptDetail.as_view()),
                           name='receipt-detail'),
                       url(r"^receipt/(?P<pk>[-_\w]+)/update/$",
                           permission_required('aircraft.change_aircraft')(views.ReceiptUpdate.as_view()),
                           name="receipt-update"),

                       # Invoice
                       url(r"^$", login_required(views.InvoiceList.as_view()), name="invoice-list"),
                       url(r"^add/$", permission_required('aircraft.add_aircraft')(views.InvoiceCreate.as_view()),
                           name="invoice-create"),
                       url(r'^(?P<pk>[-_\w]+)/$', login_required(views.InvoiceDetail.as_view()), name='invoice-detail'),
                       url(r"^(?P<pk>[-_\w]+)/update/$",
                           permission_required('aircraft.change_aircraft')(views.InvoiceUpdate.as_view()),
                           name="invoice-update"),
                       # PDF
                       url(r"^(?P<invoice_pk>[-_\w]+)/invoice.pdf$", views.invoice_to_pdf),

                       # API
                       url(r"^api/prepare_send_email_invoice/(?P<order_id>[0-9]+)",
                           api.send_email_invoice_to_customer,
                           name='api.send_email_invoice_to_customer'),
)

ProjectTango/invoice/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.contrib.auth.models import User
from django.utils.translation import ugettext_lazy as _
from django.core.urlresolvers import reverse

from datetime import date, timedelta

from aircraft.models.aircraft import Aircraft, AircraftType
from customer.models import Customer
from schedule.models import Event
from core.models import AccountModel


def _date_created_today():
    return date.today()


def _date_due_week():
    return date.today() + timedelta(days=7)


class Invoice(AccountModel):
    """
        Invoice for an event
        :Invoice status:
        - Entered   -> Invoice created
        - Approved  -> Invoice delivered to the customer and it is ready for paid
        - Cancel    -> Invoice was rejected
        - Paid      -> Invoice was paid
    """
    STATUS_ENTERED = 0
    STATUS_APPROVED = 1
    STATUS_CANCEL = 2
    STATUS_PAID = 3
    STATUS = (
        (STATUS_ENTERED, _('Entered')),
        (STATUS_APPROVED, _('Approved')),
        (STATUS_CANCEL, _('Cancel')),
        (STATUS_PAID, _('Paid')),
    )

    customer_name = models.CharField(max_length=64)
    customer_address = models.CharField(max_length=64)
    customer_zip = models.CharField(max_length=10,
                                    blank=True,
                                    default='')
    customer_city = models.CharField(max_length=64)

    event_title = models.CharField(max_length=255)
    event_start = models.DateTimeField()
    event_end = models.DateTimeField()

    aircraft_mark = models.CharField(max_length=20)
    aircraft_takeoff_cost = models.DecimalField(decimal_places=4,
                                                max_digits=17)
    aircraft_type = models.CharField(max_length=255)
    pilot_name = models.CharField(max_length=128, blank=True)

    date_created = models.DateField(default=_date_created_today)
    due_date = models.DateField(verbose_name=_('Payment due date'), default=_date_due_week)
    status = models.IntegerField(choices=STATUS,
                                 default=STATUS_ENTERED)
    discount = models.DecimalField(max_digits=5,
                                   decimal_places=2,
                                   default=0.00)
    passengers_number = models.PositiveIntegerField(default=0)
    comment = models.TextField(blank=True,
                               null=True)
    tax = models.ForeignKey('Tax')

    # references if exist
    customer = models.ForeignKey(Customer,
                                 blank=True,
                                 null=True,
                                 related_name="invoice_customer",
                                 on_delete=models.SET_NULL)
    event = models.OneToOneField(Event,
                                 blank=True,
                                 null=True,
                                 related_name="invoice_event",
                                 on_delete=models.SET_NULL)
    pilot = models.ForeignKey(User,
                              blank=True,
                              null=True,
                              related_name="invoice_pilot",
                              on_delete=models.SET_NULL)
    aircraft = models.ForeignKey(Aircraft,
                                 blank=True,
                                 null=True,
                                 related_name="invoice_aircraft",
                                 on_delete=models.SET_NULL)

    def __str__(self):
        return "#{id:06d}".format(id=self.id)

    def extras_total_no_tax(self):
        return sum(extra.total() for extra in self.invoice_extras.all())

    def total_no_tax(self):
        return self.extras_total_no_tax() + self.aircraft_takeoff_cost

    def total_no_tax_discount(self):
        return self.total_no_tax() - (self.total_no_tax() * self.discount / 100) if self.discount != 0 \
            else self.total_no_tax()

    def total(self):
        return self.total_no_tax_discount() + ((self.tax.value / 100) * self.total_no_tax_discount())

    def amount_outstanding(self):
        return self.total() - sum(receipt.amount for receipt in self.invoice_receipt.all())

    def get_absolute_url(self):
        return reverse('invoice-detail', kwargs={'pk': self.pk})


class Extras(models.Model):
    invoice = models.ForeignKey(Invoice, related_name='invoice_extras')
    quantity = models.PositiveIntegerField(default=1)
    description = models.TextField()
    unit_price = models.DecimalField(max_digits=17,
                                     decimal_places=4,
                                     default=0.00)

    def __str__(self):
        return "{0} x{1}".format(self.description, self.quantity)

    def total(self):
        return self.quantity * self.unit_price


class Tax(models.Model):
    name = models.CharField(max_length=64)
    value = models.DecimalField(max_digits=5,
                                decimal_places=2,
                                default=10.00)
    active = models.BooleanField(default=False)

    def __str__(self):
        return "{0} - {1}%".format(self.name, self.value)


class Receipt(AccountModel):
    PAYMENT_CASH = 0
    PAYMENT_EFTPOS = 1
    PAYMENT_CREDITCARD = 2
    PAYMENT_ONLINE = 3
    PAYMENT_METHOD = (
        (PAYMENT_CASH, _('Cash')),
        (PAYMENT_EFTPOS, _('Eftpos')),
        (PAYMENT_CREDITCARD, _('Credit Card')),
        (PAYMENT_ONLINE, _('Online')),
    )

    invoice = models.ForeignKey(Invoice, related_name='invoice_receipt')
    date = models.DateTimeField(auto_now_add=True)
    amount = models.DecimalField(max_digits=17,
                                 decimal_places=4,
                                 default=0.00)
    received_by = models.IntegerField(max_length=128, choices=PAYMENT_METHOD)

    def __str__(self):
        return "{0}, {1} [{2}]".format(self.invoice, self.date, self.amount)

    def get_absolute_url(self):
        return reverse('receipt-detail', kwargs={'pk': self.pk})

ProjectTango/invoice/templates/invoice/base.html
{% extends "core/base.html" %}

{% block head_title %}Invoice{% endblock %}

ProjectTango/invoice/templates/invoice/invoice_create.html
{% extends "invoice/base.html" %}
{% load crispy_forms_tags %}

{% block content %}
    <h4>Create/Update an Invoice</h4>

    <form action="" method="post">
        {% crispy form form.helper %}
        <fieldset>
            <legend>Extra</legend>
            {% crispy extras_formset extras_formset.form.helper %}
        </fieldset>
        <div class="button-holder">
            <input name="submit" value="Save" class="submit button" id="submit-id-submit" type="submit">
        </div>
    </form>

{% endblock %}

{% block post_extra_js %}
    <script>
        $(function () {
            ($('select[name=customer]').change(function () {
                $.ajax({
                    url: "/customer/api/customers/" + $(this).val() + "/",
                    method: "GET"
                }).done(function (data) {
                    $('input[name=customer_name]').val(data.name + " " + data.company);
                    $('input[name=customer_address]').val(data.address);
                    $('input[name=customer_zip]').val(data.zipcode);
                    $('input[name=customer_city]').val(data.city);
                });
            }));

            ($('select[name=event]').change(function () {
                $.ajax({
                    url: "/schedule/api/events/" + $(this).val() + "/",
                    method: "GET"
                }).done(function (data) {
                    $('input[name=event_title]').val(data.title);
                    $('input[name=event_start]').val(data.start);
                    $('input[name=event_end]').val(data.end);
                });
            }));

            ($('select[name=aircraft]').change(function () {
                $.ajax({
                    url: "/aircraft/api/aircrafts/" + $(this).val() + "/",
                    method: "GET"
                }).done(function (data) {
                    $('input[name=aircraft_mark]').val(data.aircraft_mark);
                    $('input[name=aircraft_takeoff_cost]').val(data.takeoff_cost);
                    $('input[name=aircraft_type]').val(data.aircraft_type_name);
                });
            }));

            ($('select[name=pilot]').change(function () {
                $('input[name=pilot_name]').val($(this).find(":selected").text());
            }));
        })
    </script>
{% endblock %}

ProjectTango/invoice/templates/invoice/invoice_detail.html
{% extends "invoice/base.html" %}

{% block content %}
    <h4>Invoice no. {{ object }}
        <small>created {{ object.date_created }}</small>
    </h4>

    <div class="row">
        <div class="large-12 columns">
            <h6 class="subheader">Customer information</h6>
            <table>
                <thead>
                <tr>
                    <th width="200">Name</th>
                    <th width="200">Address</th>
                    <th width="100">Zip code</th>
                    <th width="200">City</th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td>{{ object.customer_name }}</td>
                    <td>{{ object.customer_address }}</td>
                    <td>{{ object.customer_zip }}</td>
                    <td>{{ object.customer_city }}</td>
                </tr>
                </tbody>
            </table>
        </div>
    </div>

    <div class="row">
        <div class="large-12 columns">
            <h6 class="subheader">Event information</h6>
            <table>
                <thead>
                <tr>
                    <th width="250">Title</th>
                    <th width="225">Start</th>
                    <th width="225">End</th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td>{{ object.event_title }}</td>
                    <td>{{ object.event_start|date:"SHORT_DATETIME_FORMAT" }}</td>
                    <td>{{ object.event_end|date:"SHORT_DATETIME_FORMAT" }}</td>
                </tr>
                </tbody>
            </table>
        </div>
    </div>

    <div class="row">
        <div class="large-12 columns">
            <h6 class="subheader">Aircraft information</h6>
            <table>
                <thead>
                <tr>
                    <th width="200">Pilot</th>
                    <th width="150">Mark</th>
                    <th width="200">Type</th>
                    <th width="150">Takeoff cost</th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td>{{ object.pilot|default:"-" }}</td>
                    <td>{{ object.aircraft_mark }}</td>
                    <td>{{ object.aircraft_type }}</td>
                    <td>${{ object.aircraft_takeoff_cost|floatformat:"2" }}</td>
                </tr>
                </tbody>
            </table>
        </div>
    </div>

    <div class="row">
        <div class="large-12 columns">
            <h6 class="subheader">Extras</h6>
            <table>
                <thead>
                <tr>
                    <th width="100">Quantity</th>
                    <th width="300">Description</th>
                    <th width="150">Unit price</th>
                    <th width="150">Total</th>
                </tr>
                </thead>
                <tbody>
                {% for extra in invoice.invoice_extras.all %}
                    <tr>
                        <td>{{ extra.quantity }}</td>
                        <td>{{ extra.description }}</td>
                        <td>${{ extra.unit_price|floatformat:"2" }}</td>
                        <td>${{ extra.total|floatformat:"2" }}</td>
                    </tr>
                {% endfor %}
                <tfoot>
                <tr>
                    <td colspan="3"></td>
                    <td>${{ object.extras_total_no_tax|floatformat:"2" }}</td>
                </tr>
                </tfoot>
                </tbody>
            </table>
        </div>
    </div>

    <div class="row">
        <div class="large-12 columns">
            <h6 class="subheader">Payment information</h6>
            <table>
                <thead>
                <tr>
                    <th width="550">Ingredient</th>
                    <th width="150">Costs</th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td>Aircraft</td>
                    <td>${{ object.aircraft_takeoff_cost|floatformat:"2" }}</td>
                </tr>
                <tr>
                    <td>Extras</td>
                    <td>${{ object.extras_total_no_tax|floatformat:"2" }}</td>
                </tr>
                <tr>
                    <td>Subtotal</td>
                    <td>${{ object.extras_total_no_tax|add:object.aircraft_takeoff_cost|floatformat:"2" }}</td>
                </tr>
                <tr>
                    <td>Discount ({{ object.discount }}%)</td>
                    <td>${{ object.total_no_tax_discount|floatformat:"2" }}</td>
                </tr>
                <tr>
                    <td>Tax</td>
                    <td>{{ object.tax.value }}%</td>
                </tr>
                <tr>
                    <td><strong>Total</strong></td>
                    <td><strong>${{ object.total|floatformat:"2" }}</strong></td>
                </tr>
                <tr><td></td><td></td></tr>
                <tr>
                    <td><strong>Amount outstanding</strong></td>
                    <td><strong>${{ object.amount_outstanding|floatformat:2 }}</strong></td>
                </tr>
                </tbody>
            </table>
        </div>
    </div>

    <div class="row">
        <div class="large-12 columns">
            <h6 class="subheader">Receipts</h6>
            <table>
                <thead>
                <tr>
                    <th width="100">ID</th>
                    <th width="200">Received by</th>
                    <th width="250">Date</th>
                    <th width="150">Amount</th>

                </tr>
                </thead>
                <tbody>
                {% for receipt in object.invoice_receipt.all %}
                    <tr>
                        <td><a href="{% url 'receipt-update' receipt.id %}" title="edit">edit</a></td>
                        <td>{{ receipt.get_received_by_display }}</td>
                        <td>{{ receipt.date|date:"SHORT_DATETIME_FORMAT" }}</td>
                        <td>${{ receipt.amount|floatformat:2 }}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
            <a href="{% url 'receipt-create' %}?invoice={{ object.id }}" class="button tiny success"
               id="send_email_invoice">Write a receipt</a>

        </div>
    </div>


{% endblock %}

{% block post_extra_js %}
    <script>
        $(function () {
            $('#invoice_msg').hide();
            $('#send_email_invoice').on('click', function () {
                $('#preloader').delay(100).fadeIn('slow');
                $.ajax({
                    url: "{% url 'api.send_email_invoice_to_customer' order_id=object.id %}",
                    method: "GET"
                }).done(function (data) {
                    alert(data.message);
                }).always(function () {
                    $('#preloader').delay(100).fadeOut('slow');
                });
            });
        });
    </script>
{% endblock %}

ProjectTango/invoice/templates/invoice/invoice_list.html
{% extends "invoice/base.html" %}

{% block content %}
    <h4>Invoice</h4>
    <table>
        <thead>
        <th width="100">#id</th>
        <th width="300">Customer</th>
        <th width="100">Status</th>
        <th width="100" class="text-right">Total</th>
        </thead>
        <tbody>
        {% for invoice in invoice_list %}
            <tr>
                <td><a href="{% url "invoice-detail" pk=invoice.pk %}">{{ invoice }}</a></td>
                <td>{{ invoice.customer_name }}</td>
                <td>{{ invoice.get_status_display }}</td>
                <td class="text-right">{{ invoice.total|floatformat:"2" }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

ProjectTango/invoice/templates/invoice/invoice_update.html
{% extends "invoice/base.html" %}
{% load crispy_forms_tags %}

{% block content %}
    <h4>Update Invoice</h4>

    {% crispy form form.helper %}

{% endblock %}

ProjectTango/invoice/templates/invoice/receipt_create.html
{% extends "invoice/base.html" %}
{% load crispy_forms_tags %}

{% block content %}
    <h4>Create/Update an Receipt</h4>

    {% crispy form form.helper %}

{% endblock %}

{% block post_extra_js %}
{% endblock %}

ProjectTango/invoice/templates/invoice/receipt_detail.html
{% extends "invoice/base.html" %}

{% block content %}
    <h4>Receipt no. {{ object.id }}
        <small>created {{ object.date }}</small>
    </h4>

    <div class="row">
        <div class="large-12 columns">
            <h6 class="subheader">Receipt information</h6>
            <table>
                <thead>
                <tr>
                    <th width="200">Invoice</th>
                    <th width="200">Amount</th>
                    <th width="200">Received by</th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td><a href="{% url "invoice-detail" pk=receipt.invoice.pk %}">{{ receipt.invoice }}</a></td>
                    <td>{{ object.amount|floatformat:2 }}</td>
                    <td>{{ object.get_received_by_display }}</td>
                </tr>
                </tbody>
            </table>
        </div>
    </div>


{% endblock %}

{% block post_extra_js %}

{% endblock %}

ProjectTango/invoice/templates/invoice/receipt_list.html
{% extends "invoice/base.html" %}

{% block content %}
    <h4>Receipt</h4>
    <table>
        <thead>
        <th width="100">Receipt</th>
        <th width="100">Invoice</th>
        <th width="150">Amount</th>
        <th width="175">Received by</th>
        <th width="175">Date</th>
        </thead>
        <tbody>
        {% for receipt in receipt_list %}
            <tr>
                <td><a href="{% url "receipt-detail" pk=receipt.pk %}">#{{ receipt.id }}</a></td>
                <td><a href="{% url "invoice-detail" pk=receipt.invoice.pk %}">{{ receipt.invoice }}</a></td>
                <td>{{ receipt.amount }}</td>
                <td>{{ receipt.received_by }}</td>
                <td>{{ receipt.date|date:"SHORT_DATETIME_FORMAT" }}</td>
            </tr>
        {% empty %}
            <tr>
                <td colspan="4">0 entries</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}